name: RealisticAnimals
version: '${project.version}'
main: com.joao.realisticanimals.RealisticAnimals
api-version: '1.20'
authors: [Super]
description: Making animals feel more realistic. Heavily inspired in Stardew Valley
commands:
  debug: